version: "3.9"

services:
  # Serviço que irá rodar o node
  backend:
    # Faz o build do Dockerfile da pasta atual e utiliza o resultado desse build
    # como a imagem do container
    build:
      context: ./backend # Caminho para a pasta do seu backend
      dockerfile: Dockerfile
    # Nome do container para facilitar execução
    container_name: medical_api
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./backend:/app
    # Lista de serviços do qual este serviço depende
    depends_on:
      # Precisa do banco funcionando antes de subir o node
      - medical_db
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3001:3001
    # Configura as variáveis de ambiente dentro do container
    env_file:
      - .env

  frontend:
    build: 
      context: ./frontend # Caminho para a pasta do seu frontend
      dockerfile: Dockerfile
    container_name: medical_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always

  medical_db:
    image: mysql
    container_name: medical_db
    environment:
      MYSQL_ROOT_PASSWORD: mushokutensei
      MYSQL_DATABASE: medical_db
      MYSQL_USER: medical_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
